### ISSUE TITLE
AFR on 23.976 - why this commit removed this display mode?

### ISSUE THREAD

**Issue by byaka** [zidootech/ZDMC#1]
https://github.com/zidootech/ZDMC/commit/a21bfe92b8b9620763328c36c960bc584b995e35#diff-ec3fcb584284ff6d5ab9a96f6dfb884eL400

i tested 16.1 version with this deleted code and AFR for floating frame-rates working correctly with it.

Can someone build ZDMC 17.6 version with this modified source?

**Comment by zidootech** [comment]
The commit still exists. Please change to branch 'zdmc-rtk-17.6'.  Or you can download the prebuilt version from here : http://www.mediafire.com/file/kvnmzg1g87wj8kv/zdmc-17.6_1295.apk

**Comment by byaka** [comment]
sorry, maybe i confused you.

Branch 17.6 (affected by linked commit) have deleted lines
```cpp
     case RES_1080P_24HZ:
        if (SysModeToResolution(RES_1080P_23HZ, &res) && (supported_resolutions[RES_1080P_23HZ] == 0)) {
            res.iWidth = m_fb_res.iWidth;
            res.iHeight = m_fb_res.iHeight;
            resolutions.push_back(res);
            supported_resolutions[RES_1080P_23HZ] = 1;
        }
        break;
```
in this case ZDMC cant output to 1080p@23fps and automatically switching to 1080p@24fps. I'm explained this problem [here](http://forum.zidoo.tv/index.php?threads/zdmc-release17-6-x8-x9s-x10.5589/page-9#post-39319).

For solving this problem we need to return this lines.

But i dont have correct env for building ZDMC so cant compile and build apk myself please.
I'm attach fixed version of `ZDMC/xbmc/windowing/egl/EGLNativeTypeRtkAndroid.cpp`.
Hope you fix my problem.

[EGLNativeTypeRtkAndroid.cpp.zip](https://github.com/zidootech/ZDMC/files/1916150/EGLNativeTypeRtkAndroid.cpp.zip)

**Comment by zidootech** [comment]
I had fixed it and built new apk, please go to release page to get it. Thanks

**Comment by byaka** [comment]
Thx!
Also add pls same mode-checking for 59fps. I know, not alot videos in this format, but its only few lines of code.

**Comment by byaka** [comment]
And can you please explain one thing - x8\x9s\x10 have realtek aarch64 cpu. Why ZDMC builded for armv7a? Just curious, kodi don't have any benefits of aarch64 so no point? i tried to build for aarch64 but have alot errors and i don't have enough knowledge to fix this.

also old ZDMC 17.6 apk is near 130mb, but latest (and also my build) only ~80mb. Is it normal? i'm tested my build few hours and not finded any problems, but maybe i missed something. 50mb vanished from apk, its strange.
